import { beforeEach, describe, expect, it, vi } from "vitest";
import { createDefaultRemediationHandler } from "./remediation-handler.js";
import type { AutoremediatorRepoConfig } from "./types.js";
import { DEFAULT_REPO_CONFIG } from "./types.js";

const { remediateFromScanMock } = vi.hoisted(() => ({
  remediateFromScanMock: vi.fn(async () => ({
    schemaVersion: "1.0",
    status: "ok",
    generatedAt: new Date().toISOString(),
    cveIds: [],
    reports: [],
    successCount: 0,
    failedCount: 0,
    errors: [],
    patchCount: 0,
  })),
}));

vi.mock("autoremediator", () => ({
  remediateFromScan: remediateFromScanMock,
}));

function makeOctokitFactory() {
  return vi.fn(async () => ({} as never));
}

function makeRepoConfigProvider(config: Partial<AutoremediatorRepoConfig> = {}) {
  return vi.fn(async () => ({ ...DEFAULT_REPO_CONFIG, ...config }));
}

describe("createDefaultRemediationHandler", () => {
  beforeEach(() => {
    remediateFromScanMock.mockClear();
  });

  it("passes repo config settings to remediateFromScan in audit mode", async () => {
    const repoConfigProvider = makeRepoConfigProvider({
      dryRun: false,
      runTests: true,
      minimumSeverity: "UNKNOWN",
      pullRequest: {
        enabled: true,
        grouping: "per-package",
        repository: "rawlings/autoremediator-demo",
        baseBranch: "main",
        branchPrefix: "autoremediator/fix",
        titlePrefix: "chore(security)",
        bodyFooter: "Generated by github-app runtime",
        draft: true,
        pushRemote: "origin",
        tokenEnvVar: "GITHUB_TOKEN",
      },
    });

    const handler = createDefaultRemediationHandler({
      octokitFactory: makeOctokitFactory(),
      repoConfigProvider,
    });

    await handler({
      eventName: "workflow_dispatch",
      deliveryId: "delivery-core-2",
      installationId: 124,
      payload: { repository: { name: "web", owner: { login: "acme" } } },
    });

    expect(remediateFromScanMock).toHaveBeenCalledTimes(1);
    expect(remediateFromScanMock).toHaveBeenCalledWith("", expect.objectContaining({
      audit: true,
      dryRun: false,
      runTests: true,
      changeRequest: expect.objectContaining({
        enabled: true,
        provider: "github",
        grouping: "per-package",
        repository: "rawlings/autoremediator-demo",
        baseBranch: "main",
        branchPrefix: "autoremediator/fix",
        titlePrefix: "chore(security)",
        bodyFooter: "Generated by github-app runtime",
        draft: true,
        pushRemote: "origin",
        tokenEnvVar: "GITHUB_TOKEN",
      }),
    }));
  });

  it("calls core scan remediation in audit mode with default repo config", async () => {
    const repoConfigProvider = makeRepoConfigProvider({
      dryRun: false,
      minimumSeverity: "UNKNOWN",
    });

    const handler = createDefaultRemediationHandler({
      octokitFactory: makeOctokitFactory(),
      repoConfigProvider,
    });

    await handler({
      eventName: "check_suite",
      deliveryId: "delivery-core-1",
      installationId: 123,
      payload: { repository: { name: "web", owner: { login: "acme" } } },
    });

    expect(remediateFromScanMock).toHaveBeenCalledTimes(1);
    expect(remediateFromScanMock).toHaveBeenCalledWith("", expect.objectContaining({
      audit: true,
      dryRun: false,
      runTests: false,
      changeRequest: undefined,
    }));
  });

  it("filters CVEs deterministically when minimum severity is HIGH", async () => {
    const repoConfigProvider = makeRepoConfigProvider({ minimumSeverity: "HIGH" });

    const handler = createDefaultRemediationHandler({
      octokitFactory: makeOctokitFactory(),
      repoConfigProvider,
      auditFindingProvider: async () => [
        { cveId: "CVE-2024-0003", severity: "LOW" },
        { cveId: "CVE-2024-0002", severity: "CRITICAL" },
        { cveId: "CVE-2024-0001", severity: "HIGH" },
        { cveId: "CVE-2024-0002", severity: "HIGH" },
      ],
    });

    await handler({
      eventName: "check_suite",
      payload: { repository: { name: "web", owner: { login: "acme" } } },
    });

    expect(remediateFromScanMock).toHaveBeenCalledTimes(1);
    const mockCalls = remediateFromScanMock.mock.calls as unknown as Array<[string, Record<string, unknown>]>;
    const [inputPath, options] = mockCalls[0];
    expect(inputPath).toContain("filtered-findings.sarif");
    expect(options).toMatchObject({
      format: "sarif",
      audit: false,
      dryRun: true,
      runTests: false,
      changeRequest: undefined,
    });
  });

  it("returns success without remediation when no CVEs meet threshold", async () => {
    const repoConfigProvider = makeRepoConfigProvider({ minimumSeverity: "CRITICAL" });

    const handler = createDefaultRemediationHandler({
      octokitFactory: makeOctokitFactory(),
      repoConfigProvider,
      auditFindingProvider: async () => [{ cveId: "CVE-2024-5555", severity: "HIGH" }],
    });

    const result = await handler({
      eventName: "workflow_dispatch",
      payload: { repository: { name: "web", owner: { login: "acme" } } },
    });

    expect(remediateFromScanMock).not.toHaveBeenCalled();
    expect(result).toEqual({
      status: "success",
      reason: "No CVEs matched minimum severity filter",
    });
  });

  it("processes push events with the same logic as check_suite", async () => {
    const repoConfigProvider = makeRepoConfigProvider({
      dryRun: false,
      runTests: false,
      minimumSeverity: "UNKNOWN",
    });

    const handler = createDefaultRemediationHandler({
      octokitFactory: makeOctokitFactory(),
      repoConfigProvider,
    });

    await handler({
      eventName: "push",
      deliveryId: "delivery-push-handler",
      installationId: 123,
      payload: { repository: { name: "web", owner: { login: "acme" } } },
    });

    expect(remediateFromScanMock).toHaveBeenCalledTimes(1);
    expect(remediateFromScanMock).toHaveBeenCalledWith("", expect.objectContaining({
      audit: true,
      dryRun: false,
      runTests: false,
    }));
  });

  it("ignores non-triggering events", async () => {
    const handler = createDefaultRemediationHandler({
      octokitFactory: makeOctokitFactory(),
      repoConfigProvider: makeRepoConfigProvider(),
    });

    const result = await handler({
      eventName: "issues",
      payload: {},
    });

    expect(remediateFromScanMock).not.toHaveBeenCalled();
    expect(result).toBeUndefined();
  });
});

