import { execa } from "execa";
import type {
  ChangeRequestOptions,
  ChangeRequestResult,
  RemediationReport,
} from "../../platform/types.js";

interface ChangeRequestPlan {
  cveIds: string[];
  packageNames: string[];
  title: string;
  body: string;
}

function sanitizeBranchToken(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9._/-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
}

function buildPlan(reports: RemediationReport[]): ChangeRequestPlan {
  const cveIds = Array.from(new Set(reports.map((report) => report.cveId)));
  const packageNames = Array.from(
    new Set(
      reports.flatMap((report) => report.results.map((result) => result.packageName))
    )
  );

  const titleSuffix = cveIds.length === 1 ? cveIds[0]! : `${cveIds.length} CVEs`;
  const title = `security remediation: ${titleSuffix}`;
  const body = [
    "Automated remediation generated by autoremediator.",
    "",
    `CVEs: ${cveIds.join(", ")}`,
    `Packages: ${packageNames.join(", ")}`,
  ].join("\n");

  return {
    cveIds,
    packageNames,
    title,
    body,
  };
}

function resolveProvider(options: ChangeRequestOptions): "github" | "gitlab" {
  return options.provider ?? "github";
}

function resolveGrouping(options: ChangeRequestOptions): "all" {
  if (options.grouping && options.grouping !== "all") {
    throw new Error(
      "changeRequest.grouping currently supports only 'all' for deterministic branch creation."
    );
  }
  return "all";
}

async function detectCurrentBranch(cwd: string): Promise<string> {
  const result = await execa("git", ["rev-parse", "--abbrev-ref", "HEAD"], {
    cwd,
    stdio: "pipe",
  });
  return result.stdout.trim();
}

async function ensureRepoHasChanges(cwd: string): Promise<boolean> {
  const diff = await execa("git", ["status", "--porcelain"], {
    cwd,
    stdio: "pipe",
  });
  return diff.stdout.trim().length > 0;
}

function toBranchName(prefix: string, cveIds: string[]): string {
  const token = sanitizeBranchToken(cveIds.join("-") || "remediation");
  return `${sanitizeBranchToken(prefix)}/${token}-${Date.now()}`;
}

async function createGitHubRequest(params: {
  cwd: string;
  repository?: string;
  head: string;
  base: string;
  title: string;
  body: string;
  draft?: boolean;
}): Promise<string | undefined> {
  const args = ["pr", "create", "--head", params.head, "--base", params.base, "--title", params.title, "--body", params.body];
  if (params.repository) {
    args.push("--repo", params.repository);
  }
  if (params.draft) {
    args.push("--draft");
  }

  const result = await execa("gh", args, {
    cwd: params.cwd,
    stdio: "pipe",
  });
  return result.stdout.trim() || undefined;
}

async function createGitLabRequest(params: {
  cwd: string;
  repository?: string;
  source: string;
  target: string;
  title: string;
  body: string;
  draft?: boolean;
}): Promise<string | undefined> {
  const args = [
    "mr",
    "create",
    "--source-branch",
    params.source,
    "--target-branch",
    params.target,
    "--title",
    params.title,
    "--description",
    params.body,
  ];
  if (params.repository) {
    args.push("-R", params.repository);
  }
  if (params.draft) {
    args.push("--draft");
  }

  const result = await execa("glab", args, {
    cwd: params.cwd,
    stdio: "pipe",
  });
  return result.stdout.trim() || undefined;
}

export async function createChangeRequestsForReports(params: {
  cwd: string;
  options: ChangeRequestOptions;
  reports: RemediationReport[];
}): Promise<ChangeRequestResult[]> {
  const { cwd, options, reports } = params;
  const provider = resolveProvider(options);
  const grouping = resolveGrouping(options);
  const plan = buildPlan(reports);

  const titlePrefix = options.titlePrefix?.trim();
  const title = titlePrefix ? `${titlePrefix} ${plan.title}` : plan.title;
  const body = options.bodyFooter ? `${plan.body}\n\n${options.bodyFooter}` : plan.body;

  try {
    const hasChanges = await ensureRepoHasChanges(cwd);
    if (!hasChanges) {
      return [
        {
          provider,
          grouping,
          repository: options.repository,
          branchName: "",
          title,
          body,
          created: false,
          cveIds: plan.cveIds,
          packageNames: plan.packageNames,
          error: "No repository changes to include in change request.",
        },
      ];
    }

    const baseBranch = options.baseBranch ?? (await detectCurrentBranch(cwd));
    const branchPrefix = options.branchPrefix ?? "autoremediator";
    const branchName = toBranchName(branchPrefix, plan.cveIds);
    const pushRemote = options.pushRemote ?? "origin";

    await execa("git", ["checkout", "-b", branchName], { cwd, stdio: "pipe" });
    await execa("git", ["add", "-A"], { cwd, stdio: "pipe" });
    await execa("git", ["commit", "-m", title], { cwd, stdio: "pipe" });
    await execa("git", ["push", "-u", pushRemote, branchName], { cwd, stdio: "pipe" });

    const url =
      provider === "github"
        ? await createGitHubRequest({
            cwd,
            repository: options.repository,
            head: branchName,
            base: baseBranch,
            title,
            body,
            draft: options.draft,
          })
        : await createGitLabRequest({
            cwd,
            repository: options.repository,
            source: branchName,
            target: baseBranch,
            title,
            body,
            draft: options.draft,
          });

    return [
      {
        provider,
        grouping,
        repository: options.repository,
        branchName,
        title,
        body,
        created: true,
        draft: options.draft,
        url,
        cveIds: plan.cveIds,
        packageNames: plan.packageNames,
      },
    ];
  } catch (error) {
    return [
      {
        provider,
        grouping,
        repository: options.repository,
        branchName: "",
        title,
        body,
        created: false,
        draft: options.draft,
        cveIds: plan.cveIds,
        packageNames: plan.packageNames,
        error: error instanceof Error ? error.message : String(error),
      },
    ];
  }
}
